# Generated by Django 4.2.23 on 2025-11-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Numerical vector representation for AI matching', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parsed_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of detected skills extracted from the resume'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted text content from the uploaded resume', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
