# Generated by Django 4.2.23 on 2025-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ai_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ai_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
