# Generated by Django 4.2.23 on 2025-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_ai_skills_studentprofile_ai_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='ai_skills',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use ResumeAnalysis model', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ai_status',
            field=models.CharField(default='pending', help_text='DEPRECATED: Use ResumeAnalysis model', max_length=50),
        ),
    ]
